### ISSUE TITLE
Mudança do Nome

### ISSUE THREAD

**Issue by brunooomelo** [DenoBrasil/deno-brazil-forum#1]
Acho mais viável o nome ser apenas **forum**.

**Comment by LauraBeatris** [comment]
Hi @brunooomelo  

Our forum will be focused on the **Brazilian community** 
Since it's not gonna be the core forum doesn't make sense to remove the country of the repo name. 
Also, we have to think that Deno may create a core forum. 

Thanks for contributing 🚀

**Comment by brunooomelo** [comment]
Eu entendo.
como a ORG é **DenoBrasil**, creio que o pessoal não iria confundir **forum** do **DenoBrasil** com um futuro forum do **Deno**.

Apenas minha opinião.
🤘🏼

**Comment by pedro-lb** [comment]
Hey @brunooomelo !

We've updated the name to `deno-forum` 💯
